---
title: '**The Finnish Top 0.4 Percent**: An Exploration of Top Tax Shares in Finland
  from 2009 to 2013'
author: "Kyle Ott and Cornelius Schneider"
date: "12 December 2014"
output:
  pdf_document:
    number_sections: yes
    toc: yes
bibliography:
- main1.bib
- packages1.bib
---
\pagebreak
```{r, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
pkgs <- c('httr', 'dplyr', 'XML', 'ggplot2', 'stringr', 'car', 'devtools', 'rsdmx', 'stargazer', 'knitr', 'tidyr', 'reshape2', 'sandwich', 'lmtest', 'plm' )
repmis::LoadandCite(pkgs, file = 'packages1.bib')

# set your working directory here
setwd("/Users/Kyle/Dropbox/!Fall_2014/Collab_Data/Final_Project/")

##################################
# Final Assignment: Data Science Course
# Kyle Ott & Cornelius Schneider
# December 12, 2014
##################################

# Load packages
library(httr)
library(dplyr)
library(XML)
library(ggplot2)
library(stringr)
library(car)
library(devtools)
library(rsdmx)
library(stargazer)
library(knitr)
library(tidyr)
library(reshape2)
library(sandwich)
library(lmtest)
library(plm)

load("cleaned.RData")

```

#Introduction




Share Plot Goes Below
```{r, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
# figure on shares
# clean$total2009 <- with(clean, sum(clean[yr2009==1, "taxes_paid"]))
# clean$total2010 <- with(clean, sum(clean[yr2010==1, "taxes_paid"])) 
# clean$total2011 <- with(clean, sum(clean[yr2011==1, "taxes_paid"]))  
# clean$total2012 <- with(clean, sum(clean[yr2012==1, "taxes_paid"])) 
# clean$total2013 <- with(clean, sum(clean[yr2013==1, "taxes_paid"])) 

# clean$share2009 <- clean$total2009/clean$Total_Tax_Revenue
# clean$share2010 <- clean$total2010/clean$Total_Tax_Revenue 
# clean$share2011 <- clean$total2011/clean$Total_Tax_Revenue 
# clean$share2012 <- clean$total2012/clean$Total_Tax_Revenue 
# clean$share2013 <- clean$total2013/clean$Total_Tax_Revenue 
# since we only have 5 datapoints, easier to graph manually...

share <- c(0.04898281, 0.06022747, 0.06752648, 0.06347982, 0.0770184)
year <- c(2009, 2010, 2011, 2012, 2013)
shares <- data.frame(year, share)

dev.off()
```
```{r, results='asis', echo=FALSE, error=FALSE, warning=FALSE}
sharefigure <- qplot(shares$year, shares$share, caption='\n Top 0.4% Share of Total Paid Finnish Taxes', ylim=c(0.04, 0.08), geom='line', ylab='Total Finnish Taxes Share Paid by Top 0.4%\n', xlab='\nYear')
sharefigure + theme_bw(base_size = 13)
```

#Literature Review

#Dataset
```{r, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
cleaned2 <- group_by(cleaned, year)


obs_all <- tally(cleaned2)
t1_totinc <- summarise(cleaned2, mean1=mean(total_inc),median1=median(total_inc))
t1_tottax <- summarise(cleaned2, mean2=mean(taxes_paid),median2=median(taxes_paid))
t1_rat <- summarise(cleaned2, mean3=mean(ratio),median3=median(ratio))

t1a <- merge(obs_all, t1_totinc,
                  by = c('year'))
t1b <- merge(t1a, t1_tottax,
             by = c('year'))
t1c <- merge(t1b, t1_rat,
             by = c('year'))

load("clean.RData")

obs_all_sum <- tally(clean)
t1_totinc_sum <- summarise(clean, mean1=mean(total_inc),median1=median(total_inc))
t1_tottax_sum <- summarise(clean, mean2=mean(taxes_paid),median2=median(taxes_paid))
t1_rat_sum <- summarise(clean, mean3=mean(ratio),median3=median(ratio))

obs_all_sum$year <- c('All')
t1_totinc_sum$year <- c('All')
t1_tottax_sum$year <- c('All')
t1_rat_sum$year <- c('All')

t1a_sum <- merge(obs_all_sum, t1_totinc_sum,
             by = c('year'))
t1b_sum <- merge(t1a_sum, t1_tottax_sum,
             by = c('year'))
t1c_sum <- merge(t1b_sum, t1_rat_sum,
             by = c('year'))

summarytableTS <- rbind(t1c, t1c_sum)
```

Summary Stats Table

```{r, results='asis', echo=FALSE, error=FALSE, warning=FALSE}
knitr::kable(summarytableTS, align ='c', digits = 0, format='latex', 
             col.names=c("Year", "N", "Ave Inc (E)", "Med Inc (E)",
                         "Ave Paid (E)", "Med Paid (E)",
                         "Mean Tax (%)", "Med Tax (%)"))
```

```{r, results='asis', echo=FALSE, error=FALSE, warning=FALSE}

clean$year2 <- as.character(clean$year)
m <- ggplot(clean, aes(x = ratio, y= ..count.., group=year2))
m + geom_density(aes(colour=year2)) +
  scale_colour_brewer(palette="Set1") +
  theme_bw(base_size = 13) +
  xlab("\nAverage Tax Rate (%)") +
  ylab("Count\n") +
  ggtitle("Observation Counts of Average Tax Rate by Year\n")
```

```{r, results='asis', echo=FALSE, error=FALSE, warning=FALSE}
m2 <- ggplot(clean, aes(x = log(taxes_paid), y= ..count.., group=year2))
m2 + geom_density(aes(colour=year2)) +
  scale_colour_brewer(palette="Set1") +
  theme_bw(base_size = 13) +
  xlab("\nLog Total Income (Euros)") +
  ylab("Count\n") +
  xlim(8,18)+
  ggtitle("Observation Count of Log Total Income by Year\n")
```

Average Tax Rate in Decile Means Plot

```{r, inlcude=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
## Creating graph, bin plo like finnish top income paper

bins <- group_by(clean, year)

bins1 <- subset(bins, total_inc <= quantile(total_inc, 0.1))
binplot1 <- mutate(bins1, avetax1 = mean(ratio))
binplot1a <- summarise(binplot1, median(avetax1))

bins2 <- subset(bins, total_inc <= quantile(total_inc, 0.2))
binplot2 <- mutate(bins2, avetax2 = mean(ratio))
binplot2a <- summarise(binplot2, median(avetax2))

binplots <- merge(binplot1a, binplot2a,
               by = c('year'))

bins3 <- subset(bins, total_inc <= quantile(total_inc, 0.3))
binplot3 <- mutate(bins3, avetax3 = mean(ratio))
binplot3a <- summarise(binplot3, median(avetax3))

binplots <- merge(binplots, binplot3a,
                  by = c('year'))
                  
bins4 <- subset(bins, total_inc <= quantile(total_inc, 0.4))
binplot4 <- mutate(bins4, avetax4 = mean(ratio))
binplot4a <- summarise(binplot4, median(avetax4))

binplots <- merge(binplots, binplot4a,
                  by = c('year'))
bins5 <- subset(bins, total_inc <= quantile(total_inc, 0.5))
binplot5 <- mutate(bins5, avetax5 = mean(ratio))
binplot5a <- summarise(binplot5, median(avetax5))

binplots <- merge(binplots, binplot5a,
                  by = c('year'))
bins6 <- subset(bins, total_inc <= quantile(total_inc, 0.6))
binplot6 <- mutate(bins6, avetax6 = mean(ratio))
binplot6a <- summarise(binplot6, median(avetax6))

binplots <- merge(binplots, binplot6a,
                  by = c('year'))
bins7 <- subset(bins, total_inc <= quantile(total_inc, 0.7))
binplot7 <- mutate(bins7, avetax7 = mean(ratio))
binplot7a <- summarise(binplot7, median(avetax7))

binplots <- merge(binplots, binplot7a,
                  by = c('year'))
bins8 <- subset(bins, total_inc <= quantile(total_inc, 0.8))
binplot8 <- mutate(bins8, avetax8 = mean(ratio))
binplot8a <- summarise(binplot8, median(avetax8))

binplots <- merge(binplots, binplot8a,
                  by = c('year'))
bins9 <- subset(bins, total_inc <= quantile(total_inc, 0.9))
binplot9 <- mutate(bins9, avetax9 = mean(ratio))
binplot9a <- summarise(binplot9, median(avetax9))

binplots <- merge(binplots, binplot9a,
                  by = c('year'))

## melting and plotting the bins

binplots <- plyr::rename(x = binplots,
                      replace = c("median(avetax1)" = "1",
                                  "median(avetax2)" = "2",
                                  "median(avetax3)" = "3",
                                  "median(avetax4)" = "4",
                                  "median(avetax5)" = "5",
                                  "median(avetax6)" = "6",
                                  "median(avetax7)" = "7",
                                  "median(avetax8)" = "8",
                                  "median(avetax9)" = "9"
                      ))

binplots2 <- melt(binplots, id=c("year"))
binplots2 <- group_by(binplots2, year)

binplots2$year <- as.character(binplots2$year)

ggplot(data = binplots2, aes(x = variable,y = value, group=year)) +
          geom_line(aes(color = year)) + theme_bw(base_size = 13) +
          xlab("\nDecile Bin") +
          ylab("Average Tax Rate (%)\n") +
          ggtitle("Average Tax Rate by Deciles\n") +
          scale_colour_brewer(palette="Set1")
```




#Methodology

#Results

```{r, inlcude=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
load("cleaned.RData")
M1 <- lm(log(avg_inc) ~ log(net_of_tax), data = cleaned, na.action = NULL)
# we have strong autocorr, so we use newey-west SE's
# M1a <- coeftest(M1,vcov=NeweyWest)
# stargazer only prints newey west results of coeff and SE only, no other info
M2 <- lm(log(avg_inc) ~ log(net_of_tax) + year,data = cleaned, na.action = NULL)
# due to problems with martix calculations, we cannot run newey west SW for M2
# therefore, we will argue that our coefficients are right, but the SE will be different
# Create cleaner covariate labels
labels <- c('Elasticity', 'Time Trend')
```

Time Series Results 

```{r, results='asis', echo=FALSE, error=FALSE, warning=FALSE}
stargazer::stargazer(M1, M2, covariate.labels = labels,
                     title = 'Time Series Elasticities',
                     column.labels = c("Without Time Trend", "With Time Trend"),
                     dep.var.labels = c("Log of Average Taxable Income"),
                     type = 'latex', header = FALSE)
```

Panel Result

```{r, inlcude=FALSE, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

# from creating panel dataset
load("panelmodel3.RData")
  
#OLS
ols1 <- lm(log(dep) ~ log(indep), data=panelmodel3)
summary(ols1)
confint(ols1)
# Durbin-Watson test for autocorrelation
# dwt(ols1)
# we do not have strong autocorr

# panelmodel3$id2 <- as.character(panelmodel3$id2)
# still can't get the panel to run using id2, using justname from now on

# Fixed

fixed <- plm(log(dep) ~ log(indep), data=panelmodel3, index=c("justname", "year"), model="within")
# summary(fixed)
# confint(fixed)
# Testing for fixed effects, null: OLS better than fixed
# pFtest(fixed, ols1) 

#BP LM test of cross-sectional dependence
# pcdtest(fixed, test = c("lm"))
# yes cross-sectional dependence?

# testing for serial correlation
# pbgtest(fixed)
# yes serial correlation?

# testing for heterosk, BP test
# bptest(dep ~ indep + factor(justname), data = panelmodel3, studentize=F)

# Create cleaner covariate labels
labels2 <- c('Elasticity')
```

Why does the summary show up?

```{r, results='asis', echo=FALSE, error=FALSE, warning=FALSE}
stargazer::stargazer(ols1, fixed, covariate.labels = labels2,
                     title = 'Panel Elasticities',
                     column.labels = NULL,
                     dep.var.labels = c("Log of Average Taxable Income"),
                     type = 'latex', header = FALSE)
```

#Discussion

#Conclusion

#References
