---
title: "Untitled"
author: "Ott and Schneider"
date: "December 4, 2014"
output: pdf_document
---

## Key Findings

```{r, inlcude=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
library(httr)
library(dplyr)
library(XML)
library(ggplot2)
library(stringr)
library(car)
library(devtools)
library(rsdmx)
library(stargazer)
library(knitr)
library(CausalImpact)
library(sandwich)
library(lmtest)
library(plm)

setwd("/Users/Kyle/Dropbox/!Fall_2014/Collab_Data/Final_Project/")
load("cleaned.RData")
M1 <- lm(log(avg_inc) ~ log(net_of_tax), data = cleaned, na.action = NULL)
# we have strong autocorr, so we use newey-west SE's
M1a <- coeftest(M1,vcov=NeweyWest)
M2 <- lm(log(avg_inc) ~ log(net_of_tax) + year,data = cleaned, na.action = NULL)
# Create cleaner covariate labels
labels <- c('Elasticity', 'Time Trend')
```

```{r, results='asis', echo=FALSE, error=FALSE, warning=FALSE}
stargazer::stargazer(M1a, M2, covariate.labels = labels,
                     model.names = FALSE,
                     dep.var.labels.include = FALSE,
                     title = 'Time Series Elasticities',
                     type = 'latex', header = FALSE)
```